// <auto-generated />
namespace HGV.Nullifier.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TalentHeroStats : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TalentHeroStats));
        
        string IMigrationMetadata.Id
        {
            get { return "201811202349316_TalentHeroStats"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
