// <auto-generated />
namespace HGV.Nullifier.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EqualizeTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EqualizeTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201903021631002_EqualizeTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
